import { MovieInterface } from '../types/movie.interface';

export const MOVIES_MOCK: MovieInterface[] = [
    {
        Title: 'The Avengers',
        Year: '2012',
        Rated: 'PG-13',
        Released: '04 May 2012',
        Runtime: '143 min',
        Genre: 'Action, Adventure, Sci-Fi',
        Director: 'Joss Whedon',
        Writer: 'Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)',
        Actors: 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth',
        Plot: `Earth's mightiest heroes must come together and learn to fight as a team
    if they are going to stop the mischievous Loki and his alien army from enslaving humanity.`,
        Language: 'English, Russian, Hindi',
        Country: 'USA',
        Awards: 'Nominated for 1 Oscar. Another 38 wins & 79 nominations.',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '8.0/10' },
            { Source: 'Rotten Tomatoes', Value: '92%' },
            { Source: 'Metacritic', Value: '69/100' },
        ],
        Metascore: '69',
        imdbRating: '8.0',
        imdbVotes: '1,200,683',
        Id: 'tt0848228',
        Type: 'movie',
        DVD: '25 Sep 2012',
        BoxOffice: '$623,279,547',
        Production: 'Walt Disney Pictures',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'Rocky',
        Year: '1976',
        Rated: 'PG',
        Released: '03 Dec 1976',
        Runtime: '120 min',
        Genre: 'Drama, Sport',
        Director: 'John G. Avildsen',
        Writer: 'Sylvester Stallone',
        Actors: 'Sylvester Stallone, Talia Shire, Burt Young, Carl Weathers',
        Plot: `A small-time boxer gets a supremely rare chance to fight a
    heavy-weight champion in a bout in which he strives to go the distance for his self-respect.`,
        Language: 'English',
        Country: 'USA',
        Awards: 'Won 3 Oscars. Another 17 wins & 21 nominations.',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BMTY5MDMzODUyOF5BMl5BanBnXkFtZTcwMTQ3NTMyNA@@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '8.1/10' },
            { Source: 'Rotten Tomatoes', Value: '93%' },
            { Source: 'Metacritic', Value: '70/100' },
        ],
        Metascore: '70',
        imdbRating: '8.1',
        imdbVotes: '481,300',
        Id: 'tt0075148',
        Type: 'movie',
        DVD: '07 Aug 2006',
        BoxOffice: 'N/A',
        Production: 'United Artists',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'Greta',
        Year: '2018',
        Rated: 'R',
        Released: '01 Mar 2019',
        Runtime: '98 min',
        Genre: 'Drama, Mystery, Thriller',
        Director: 'Neil Jordan',
        Writer: 'Ray Wright (screenplay by), Neil Jordan (screenplay by), Ray Wright (story by)',
        Actors: 'Isabelle Huppert, Chloë Grace Moretz, Maika Monroe, Jane Perry',
        Plot:
            "A young woman befriends a lonely widow who's harboring a dark and deadly agenda toward her.",
        Language: 'English, Hungarian, French, Korean',
        Country: 'Ireland, USA',
        Awards: 'N/A',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BOTg0OTVjYjUtOWUzYS00YjJjLWI3NWItMmVjNTBlMTE2ODJlXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '6.0/10' },
            { Source: 'Metacritic', Value: '54/100' },
        ],
        Metascore: '54',
        imdbRating: '6.0',
        imdbVotes: '15,781',
        Id: 'tt2639336',
        Type: 'movie',
        DVD: 'N/A',
        BoxOffice: 'N/A',
        Production: 'N/A',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'Captain Marvel',
        Year: '2019',
        Rated: 'PG-13',
        Released: '08 Mar 2019',
        Runtime: '123 min',
        Genre: 'Action, Adventure, Sci-Fi',
        Director: 'Anna Boden, Ryan Fleck',
        Writer:
            'Anna Boden (screenplay by), Ryan Fleck (screenplay by), Geneva Robertson-Dworet (screenplay by), Nicole Perlman (story by), Meg LeFauve (story by), Anna Boden (story by), Ryan Fleck (story by), Geneva Robertson-Dworet (story by)',
        Actors: 'Brie Larson, Samuel L. Jackson, Ben Mendelsohn, Jude Law',
        Plot:
            "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races.",
        Language: 'English',
        Country: 'USA, Australia',
        Awards: 'N/A',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BMTE0YWFmOTMtYTU2ZS00ZTIxLWE3OTEtYTNiYzBkZjViZThiXkEyXkFqcGdeQXVyODMzMzQ4OTI@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '7.0/10' },
            { Source: 'Rotten Tomatoes', Value: '78%' },
            { Source: 'Metacritic', Value: '64/100' },
        ],
        Metascore: '64',
        imdbRating: '7.0',
        imdbVotes: '359,923',
        Id: 'tt4154664',
        Type: 'movie',
        DVD: '11 Jun 2019',
        BoxOffice: 'N/A',
        Production: 'Marvel Studios',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'Happy Death Day',
        Year: '2017',
        Rated: 'PG-13',
        Released: '13 Oct 2017',
        Runtime: '96 min',
        Genre: 'Horror, Mystery, Thriller',
        Director: 'Christopher Landon',
        Writer: 'Scott Lobdell',
        Actors: 'Jessica Rothe, Israel Broussard, Ruby Modine, Charles Aitken',
        Plot:
            "A college student must relive the day of her murder over and over again, in a loop that will end only when she discovers her killer's identity.",
        Language: 'English',
        Country: 'USA',
        Awards: '1 nomination.',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BYzZhY2E5NzQtMWVmNC00YmEzLTgxZDMtNjE2YmQ4ZTZiZGZjXkEyXkFqcGdeQXVyODQxMTI4MjM@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '6.5/10' },
            { Source: 'Rotten Tomatoes', Value: '71%' },
            { Source: 'Metacritic', Value: '58/100' },
        ],
        Metascore: '58',
        imdbRating: '6.5',
        imdbVotes: '94,225',
        Id: 'tt5308322',
        Type: 'movie',
        DVD: '16 Jan 2018',
        BoxOffice: '$55,398,005',
        Production: 'Universal Studios',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'Fast Color',
        Year: '2018',
        Rated: 'PG-13',
        Released: '19 Apr 2019',
        Runtime: '100 min',
        Genre: 'Drama, Sci-Fi, Thriller',
        Director: 'Julia Hart',
        Writer: 'Julia Hart, Jordan Horowitz',
        Actors: 'Gugu Mbatha-Raw, David Strathairn, Lorraine Toussaint, Christopher Denham',
        Plot:
            'A woman is forced to go on the run when her superhuman abilities are discovered. Years after having abandoned her family, the only place she has left to hide is home.',
        Language: 'English',
        Country: 'USA',
        Awards: '1 nomination.',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BZjM0M2UxNWMtNzIzNi00NTZhLThiYTItNWFkNmVhNmE4YTlkXkEyXkFqcGdeQXVyMzAwMjMyMjY@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '5.8/10' },
            { Source: 'Rotten Tomatoes', Value: '81%' },
            { Source: 'Metacritic', Value: '65/100' },
        ],
        Metascore: '65',
        imdbRating: '5.8',
        imdbVotes: '1,627',
        Id: 'tt6418778',
        Type: 'movie',
        DVD: '16 Jul 2019',
        BoxOffice: 'N/A',
        Production: 'LD Entertainment',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'Escape Room',
        Year: '2019',
        Rated: 'PG-13',
        Released: '04 Jan 2019',
        Runtime: '99 min',
        Genre: 'Action, Adventure, Horror, Mystery, Thriller',
        Director: 'Adam Robitel',
        Writer:
            'Bragi F. Schut (screenplay by), Maria Melnik (screenplay by), Bragi F. Schut (story by)',
        Actors: 'Taylor Russell, Logan Miller, Jay Ellis, Tyler Labine',
        Plot:
            'Six strangers find themselves in a maze of deadly mystery rooms and must use their wits to survive.',
        Language: 'English',
        Country: 'USA, South Africa',
        Awards: 'N/A',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BMjQ2NDMwMTY3MF5BMl5BanBnXkFtZTgwNDg5OTc1NjM@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '6.3/10' },
            { Source: 'Rotten Tomatoes', Value: '50%' },
            { Source: 'Metacritic', Value: '48/100' },
        ],
        Metascore: '48',
        imdbRating: '6.3',
        imdbVotes: '56,046',
        Id: 'tt5886046',
        Type: 'movie',
        DVD: '23 Apr 2019',
        BoxOffice: 'N/A',
        Production: 'Columbia Pictures',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'Parabellum',
        Year: '2015',
        Rated: 'N/A',
        Released: '07 May 2015',
        Runtime: '75 min',
        Genre: 'Sci-Fi',
        Director: 'Lukas Valenta Rinner',
        Writer: 'Ana Godoy, Esteban Prado, Lukas Valenta Rinner',
        Actors: 'Eva Bianco, Pablo Seijo, Martín Shanly',
        Plot:
            'In the company of housewives, professionals and a retired tennis instructor, Hernán is part of a middle-class community that is preparing for the eventual arrival of the end of the world at a holiday resort in the marshy Tigre delta.',
        Language: 'Spanish',
        Country: 'Argentina, Austria, Uruguay',
        Awards: '1 win & 5 nominations.',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BZTM2YjQ4YjktYzA1NC00NTc1LWFlMGUtODNlN2Y0ZTJlZWY5XkEyXkFqcGdeQXVyMzcwMTY3OTU@._V1_SX300.jpg',
        Ratings: [{ Source: 'Internet Movie Database', Value: '5.3/10' }],
        Metascore: 'N/A',
        imdbRating: '5.3',
        imdbVotes: '132',
        Id: 'tt3661410',
        Type: 'movie',
        DVD: 'N/A',
        BoxOffice: 'N/A',
        Production: 'Nabis Filmgroup',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'Pokémon Detective Pikachu',
        Year: '2019',
        Rated: 'PG',
        Released: '10 May 2019',
        Runtime: '104 min',
        Genre: 'Action, Adventure, Comedy, Family, Mystery, Sci-Fi',
        Director: 'Rob Letterman',
        Writer:
            'Dan Hernandez (screenplay by), Benji Samit (screenplay by), Rob Letterman (screenplay by), Derek Connolly (screenplay by), Dan Hernandez (story by), Benji Samit (story by), Nicole Perlman (story by), Satoshi Tajiri (based on "Pokémon" created by), Ken Sugimori (based on "Pokémon" created by), Junichi Masuda (based on "Pokémon" created by), Atsuko Nishida (characters), Tomokazu Ohara (original story), Haruka Utsui (original story)',
        Actors: 'Ryan Reynolds, Justice Smith, Kathryn Newton, Bill Nighy',
        Plot:
            'In a world where people collect Pokémon to do battle, a boy comes across an intelligent talking Pikachu who seeks to be a detective.',
        Language: 'English',
        Country: 'USA, Japan, UK, Canada',
        Awards: 'N/A',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BNDU4Mzc3NzE5NV5BMl5BanBnXkFtZTgwMzE1NzI1NzM@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '6.7/10' },
            { Source: 'Rotten Tomatoes', Value: '68%' },
            { Source: 'Metacritic', Value: '53/100' },
        ],
        Metascore: '53',
        imdbRating: '6.7',
        imdbVotes: '97,681',
        Id: 'tt5884052',
        Type: 'movie',
        DVD: '23 Jul 2019',
        BoxOffice: 'N/A',
        Production: 'Warner Bros. Pictures',
        Website: 'http://detectivepikachumovie.com/',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'Glass',
        Year: '2019',
        Rated: 'PG-13',
        Released: '18 Jan 2019',
        Runtime: '129 min',
        Genre: 'Drama, Sci-Fi, Thriller',
        Director: 'M. Night Shyamalan',
        Writer: 'M. Night Shyamalan',
        Actors: 'James McAvoy, Bruce Willis, Samuel L. Jackson, Anya Taylor-Joy',
        Plot:
            'Security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities.',
        Language: 'English, Spanish',
        Country: 'USA, China',
        Awards: 'N/A',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BMTY1OTA2MjI5OV5BMl5BanBnXkFtZTgwNzkxMjU4NjM@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '6.7/10' },
            { Source: 'Rotten Tomatoes', Value: '37%' },
            { Source: 'Metacritic', Value: '43/100' },
        ],
        Metascore: '43',
        imdbRating: '6.7',
        imdbVotes: '159,195',
        Id: 'tt6823368',
        Type: 'movie',
        DVD: '16 Apr 2019',
        BoxOffice: 'N/A',
        Production: 'Universal Pictures',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'Ad Astra',
        Year: '2019',
        Rated: 'PG-13',
        Released: '20 Sep 2019',
        Runtime: '123 min',
        Genre: 'Adventure, Drama, Mystery, Sci-Fi, Thriller',
        Director: 'James Gray',
        Writer: 'James Gray, Ethan Gross',
        Actors: 'Brad Pitt, Tommy Lee Jones, Ruth Negga, Donald Sutherland',
        Plot:
            'Astronaut Roy McBride undertakes a mission across an unforgiving solar system to uncover the truth about his missing father and his doomed expedition that now, 30 years later, threatens the universe.',
        Language: 'English, Japanese, Russian',
        Country: 'USA',
        Awards: 'N/A',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BZTllZTdlOGEtZTBmMi00MGQ5LWFjN2MtOGEyZTliNGY1MzFiXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '7.0/10' },
            { Source: 'Rotten Tomatoes', Value: '83%' },
            { Source: 'Metacritic', Value: '80/100' },
        ],
        Metascore: '80',
        imdbRating: '7.0',
        imdbVotes: '52,852',
        Id: 'tt2935510',
        Type: 'movie',
        DVD: 'N/A',
        BoxOffice: 'N/A',
        Production: '20th Century Fox',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'High Life',
        Year: '2018',
        Rated: 'R',
        Released: '12 Apr 2019',
        Runtime: '113 min',
        Genre: 'Adventure, Drama, Mystery, Sci-Fi',
        Director: 'Claire Denis',
        Writer:
            'Claire Denis, Jean-Pol Fargeau, Geoff Cox (collaboration), Andrew Litvack (additional writing), Nick Laird (additional writing by)',
        Actors: 'Robert Pattinson, Juliette Binoche, André Benjamin, Mia Goth',
        Plot:
            'A father and his daughter struggle to survive in deep space where they live in isolation.',
        Language: 'English',
        Country: 'UK, France, Germany, Poland',
        Awards: 'N/A',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BMDNjN2NjYmItMjAyZi00NmNkLWJmYTQtYzcwZGRiM2RmNGNlXkEyXkFqcGdeQXVyODUxNjcxNjE@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '5.9/10' },
            { Source: 'Rotten Tomatoes', Value: '83%' },
            { Source: 'Metacritic', Value: '77/100' },
        ],
        Metascore: '77',
        imdbRating: '5.9',
        imdbVotes: '16,066',
        Id: 'tt4827558',
        Type: 'movie',
        DVD: '25 Jun 2019',
        BoxOffice: 'N/A',
        Production: 'A24',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'John Wick',
        Year: '2014',
        Rated: 'R',
        Released: '24 Oct 2014',
        Runtime: '101 min',
        Genre: 'Action, Crime, Thriller',
        Director: 'Chad Stahelski, David Leitch',
        Writer: 'Derek Kolstad',
        Actors: 'Keanu Reeves, Michael Nyqvist, Alfie Allen, Willem Dafoe',
        Plot:
            'An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him.',
        Language: 'English, Russian, Hungarian',
        Country: 'USA',
        Awards: '5 wins & 8 nominations.',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '7.4/10' },
            { Source: 'Rotten Tomatoes', Value: '87%' },
            { Source: 'Metacritic', Value: '68/100' },
        ],
        Metascore: '68',
        imdbRating: '7.4',
        imdbVotes: '479,777',
        Id: 'tt2911666',
        Type: 'movie',
        DVD: '03 Feb 2015',
        BoxOffice: 'N/A',
        Production: 'LionsGate Entertainment',
        Website: 'N/A',
        Response: 'True',
        isFavorite: false,
    },
    {
        Title: 'Alita: Battle Angel',
        Year: '2019',
        Rated: 'PG-13',
        Released: '14 Feb 2019',
        Runtime: '122 min',
        Genre: 'Action, Adventure, Sci-Fi, Thriller',
        Director: 'Robert Rodriguez',
        Writer:
            'James Cameron (screenplay by), Laeta Kalogridis (screenplay by), Yukito Kishiro (based on the graphic novel series "Gunnm" by)',
        Actors: 'Rosa Salazar, Christoph Waltz, Jennifer Connelly, Mahershala Ali',
        Plot:
            'A deactivated cyborg is revived, but cannot remember anything of her past life and goes on a quest to find out who she is.',
        Language: 'English, Spanish',
        Country: 'USA',
        Awards: 'N/A',
        Poster:
            'https://m.media-amazon.com/images/M/MV5BNzVhMjcxYjYtOTVhOS00MzQ1LWFiNTAtZmY2ZmJjNjIxMjllXkEyXkFqcGdeQXVyNTc5OTMwOTQ@._V1_SX300.jpg',
        Ratings: [
            { Source: 'Internet Movie Database', Value: '7.4/10' },
            { Source: 'Rotten Tomatoes', Value: '61%' },
            { Source: 'Metacritic', Value: '53/100' },
        ],
        Metascore: '53',
        imdbRating: '7.4',
        imdbVotes: '163,225',
        Id: 'tt0437086',
        Type: 'movie',
        DVD: '09 Jul 2019',
        BoxOffice: 'N/A',
        Production: '20th Century Fox',
        Website: 'http://www.AlitaBattleAngel.com',
        Response: 'True',
        isFavorite: false,
    },
];
