import { MovieInterface } from '../types/movie.interface';

export const MOVIES_MOCK: MovieInterface[] = [
  {
    Title: 'The Avengers',
    Year: '2012',
    Rated: 'PG-13',
    Released: '04 May 2012',
    Runtime: '143 min',
    Genre: 'Action, Adventure, Sci-Fi',
    Director: 'Joss Whedon',
    Writer: 'Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)',
    Actors: 'Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth',
    Plot: `Earth's mightiest heroes must come together and learn to fight as a team 
    if they are going to stop the mischievous Loki and his alien army from enslaving humanity.`,
    Language: 'English, Russian, Hindi',
    Country: 'USA',
    Awards: 'Nominated for 1 Oscar. Another 38 wins & 79 nominations.',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.0/10' },
      { Source: 'Rotten Tomatoes', Value: '92%' },
      { Source: 'Metacritic', Value: '69/100' },
    ],
    Metascore: '69',
    imdbRating: '8.0',
    imdbVotes: '1,200,683',
    imdbID: 'tt0848228',
    Type: 'movie',
    DVD: '25 Sep 2012',
    BoxOffice: '$623,279,547',
    Production: 'Walt Disney Pictures',
    Website: 'N/A',
    Response: 'True',
  },
  {
    Title: 'Rocky',
    Year: '1976',
    Rated: 'PG',
    Released: '03 Dec 1976',
    Runtime: '120 min',
    Genre: 'Drama, Sport',
    Director: 'John G. Avildsen',
    Writer: 'Sylvester Stallone',
    Actors: 'Sylvester Stallone, Talia Shire, Burt Young, Carl Weathers',
    Plot: `A small-time boxer gets a supremely rare chance to fight a 
    heavy-weight champion in a bout in which he strives to go the distance for his self-respect.`,
    Language: 'English',
    Country: 'USA',
    Awards: 'Won 3 Oscars. Another 17 wins & 21 nominations.',
    Poster:
      'https://m.media-amazon.com/images/M/MV5BMTY5MDMzODUyOF5BMl5BanBnXkFtZTcwMTQ3NTMyNA@@._V1_SX300.jpg',
    Ratings: [
      { Source: 'Internet Movie Database', Value: '8.1/10' },
      { Source: 'Rotten Tomatoes', Value: '93%' },
      { Source: 'Metacritic', Value: '70/100' },
    ],
    Metascore: '70',
    imdbRating: '8.1',
    imdbVotes: '481,300',
    imdbID: 'tt0075148',
    Type: 'movie',
    DVD: '07 Aug 2006',
    BoxOffice: 'N/A',
    Production: 'United Artists',
    Website: 'N/A',
    Response: 'True',
  },
];
